# Generated by Django 4.2.7 on 2023-11-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_alter_column_id_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='id',
            new_name='columid',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='task_id',
        ),
    ]
